library(data.table)
library(dplyr)
library(raster)
library(Hmisc)
library(car)
library(doBy)
library(ggcorrplot)
library(lme4)

setwd(dir="C:/Users/Francois/Documents/papier 2 - plasticité- adaptation/data_publie_Ramakers")
tab=fread("Data_PeriodSpecificReactionNorm_and_Selection.txt",header=T)
tab$temp2=scale(tab$temp,scale=F)
tab$Year2=scale(tab$Year,scale=F)
tab$Year3=cut(tab$Year,3)
model=lmer(LayDate~temp2*Year2+(1|Year),data=tab)
summary(model)
model2=lm(LayDate~temp2*Year2,data=tab)
summary(model2)
